//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahragan2019.Monastery.WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonasteryEntities : DbContext
    {
        public MonasteryEntities()
            : base("name=MonasteryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EgyptCity> EgyptCities { get; set; }
        public virtual DbSet<Monastery> Monasteries { get; set; }
        public virtual DbSet<MonasteryHistory> MonasteryHistories { get; set; }
        public virtual DbSet<MonasteryVideo> MonasteryVideos { get; set; }
        public virtual DbSet<SaintHeader> SaintHeaders { get; set; }
        public virtual DbSet<SaintParagraph> SaintParagraphs { get; set; }
        public virtual DbSet<SaintTitle> SaintTitles { get; set; }
        public virtual DbSet<SomeMonastery> SomeMonasteries { get; set; }
    }
}
