//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahragan2019.Monastery.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonasteryVideo
    {
        public int Id { get; set; }
        public int MonasteryId { get; set; }
        public string VideoSrc { get; set; }
        public string VideoDescription { get; set; }
    
        public virtual SomeMonastery SomeMonastery { get; set; }
    }
}
