//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahragan2019.Monastery.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaintParagraph
    {
        public int Id { get; set; }
        public string SaintParagraph1 { get; set; }
        public int SaintTitleId { get; set; }
    
        public virtual SaintTitle SaintTitle { get; set; }
    }
}
