//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahragan2019.Monastery.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaintHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaintHeader()
        {
            this.SaintTitles = new HashSet<SaintTitle>();
        }
    
        public int Id { get; set; }
        public string Header { get; set; }
        public int MonasteryId { get; set; }
    
        public virtual SomeMonastery SomeMonastery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaintTitle> SaintTitles { get; set; }
    }
}
