//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahragan2019.Monastery.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SomeMonastery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SomeMonastery()
        {
            this.MonasteryHistories = new HashSet<MonasteryHistory>();
            this.MonasteryVideos = new HashSet<MonasteryVideo>();
            this.SaintHeaders = new HashSet<SaintHeader>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public string Town { get; set; }
        public string Type { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
    
        public virtual EgyptCity EgyptCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonasteryHistory> MonasteryHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonasteryVideo> MonasteryVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaintHeader> SaintHeaders { get; set; }
    }
}
